CREATE DATABASE IF NOT EXISTS curso_blog;
use curso_blog;

DROP TABLE IF EXISTS articulo;
CREATE TABLE articulo (
	id INT NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(200) NOT NULL,
    extracto VARCHAR(200) NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    texto TEXT NOT NULL,
    thumb VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
